"""ingest runs and raw records

Revision ID: 3d1e14bb5580
Revises: a860ab63f293
Create Date: 2026-01-06 07:20:00.181939

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3d1e14bb5580"
down_revision: str | Sequence[str] | None = "a860ab63f293"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
